version: '3.8'

services:
  elasticsearch:
    build: ./elasticsearch
    container_name: elasticsearch
    environment:
      - node.name=elasticsearch
      - cluster.name=es-docker-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false # 운영단계에서는 보안 적용하기
    volumes:
      - es_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    networks:
      - app-network
    restart: unless-stopped

  kibana:
    image: docker.elastic.co/kibana/kibana:9.2.1
    container_name: kibana
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    networks:
      - app-network
    depends_on:
      - elasticsearch
    restart: unless-stopped

volumes:
  es_data:
    driver: local

networks:
  app-network:
    # 이미 존재한다면 external: true를 쓰겠지만,
    # 처음이라면 bridge로 유지하는 게 편해.
    driver: bridge
